### ISSUE TITLE
Error with loader returning json

### ISSUE THREAD

**Issue by stevebingsoo** [stargaze-co/react-router-typesafe#12]
I am following the 30 minute Remix tutorial and have this code that uses your library:

```
import { LoaderFunction, useLoaderData } from "react-router-typesafe";
import { json } from "@remix-run/node";
import { getContacts } from "./data";

export const loader = (async () => {
  const contacts = await getContacts();
  return json({ contacts });
}) satisfies LoaderFunction;

export default function App() {
  const { contacts } = useLoaderData<typeof loader>();
}
```

The useLoaderData line has this error:
`Property 'contacts' does not exist on type 'Omit<Response, "json"> & { json(): Promise<{ contacts: ContactRecord[]; }>; }'.`

What am I doing wrong?

**Comment by fredericoo** [comment]
Can I have a link of this tutorial? 

Remix already implements `LoaderFunction` and `useLoaderData` as generics! You can just import those from @remix-run/react` and they will be working the same way.

The reason you get the issue is that the `json` function is different in my simpler implementation of react router than in the original remix packages. 

This library was made to make development with Vite (or other SPA tooling) closer to the Remix experience with generics. If you’re on Remix already, you won’t need `react-router-typesafe` at all.

**Comment by fredericoo** [comment]
Closing as stale
